# Site settings
title: James Bergin
description: >
  Welcome. I am a embedded software engineer working for a start-up company
  that is changing the future of music creation.
url: 'http://bergin.pro/'
baseurl: '/'
google_analytics: 'UA-85981147-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'James Bergin'
  email: james@bergin.pro
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  # github_username:  joshgerdes
  linkedin_username:  jamespatrickbergin
  pdf_resume: true
  word_resume: false

links:
  email: mailto:james@bergin.pro
  linkedin_page: https://www.linkedin.com/in/jamespatrickbergin/en

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
